import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    ar: {
        home: 'الرئيسية',
        community: 'المجتمع',
        addService: 'أضف خدمتك',
        search: 'بحث',
        settings: 'الإعدادات',
        back: 'رجوع',
        premium: 'مميز',
        by: 'بواسطة',
        views: 'مشاهدة',
        contactMethods: 'طرق التواصل',
        call: 'اتصال',
        whatsapp: 'واتساب',
        email: 'إيميل',
        noContact: 'لا توجد طرق تواصل متاحة',
        reviews: 'التقييمات',
        addReview: 'أضف تقييمك',
        yourName: 'اسمك',
        yourComment: 'تعليقك',
        submitReview: 'نشر التقييم',
        noReviews: 'لا توجد تقييمات بعد',
        follow: 'متابعة',
        unfollow: 'إلغاء المتابعة',
        followers: 'المتابعون',
        following: 'يتابع',
        forYou: 'لك',
        followingFeed: 'المتابَعون',
        noPostsYet: 'لا توجد منشورات بعد',
        like: 'إعجاب',
        love: 'حب',
        comment: 'تعليق',
        share: 'مشاركة',
        reply: 'رد',
        replies: 'ردود',
        likeComment: 'إعجاب',
        writeComment: 'اكتب تعليقاً...',
        writeReply: 'اكتب رداً...',
        whatsOnMind: 'بماذا تفكر؟',
        publish: 'نشر',
        addPhoto: 'إضافة صورة',
        addMorePhotos: 'إضافة صور أخرى',
        accountSettings: 'إعدادات الحساب',
        customizeAccount: 'خصص إعدادات حسابك الشخصي',
        savedSuccessfully: 'تم الحفظ بنجاح',
        personalInfo: 'المعلومات الشخصية',
        fullNameLabel: 'الاسم الكامل',
        enterFullName: 'أدخل اسمك الكامل',
        phoneNumber: 'رقم الهاتف',
        phonePlaceholder: '05xxxxxxxx',
        emailAddress: 'البريد الإلكتروني',
        emailCannotChange: 'لا يمكن تغيير البريد الإلكتروني',
        bio: 'نبذة تعريفية',
        bioPlaceholder: 'اكتب نبذة بسيطة عنك...',
        notificationSettings: 'إعدادات الإشعارات',
        generalNotifications: 'الإشعارات العامة',
        generalNotificationsDesc: 'تلقي إشعارات عامة داخل المنصة',
        emailNotifications: 'إشعارات البريد الإلكتروني',
        emailNotificationsDesc: 'تلقي إشعارات عبر البريد الإلكتروني',
        marketingEmails: 'رسائل تسويقية',
        marketingEmailsDesc: 'تلقي عروض وتحديثات المنصة',
        securityPrivacy: 'الأمان والخصوصية',
        accountProtection: 'حماية الحساب',
        protectedByGoogle: 'حسابك محمي عبر تسجيل الدخول الآمن',
        googleAuthProtected: 'الحساب محمي',
        saving: 'جاري الحفظ...',
        saveSettings: 'حفظ الإعدادات',
        welcome: 'مرحباً بك',
        selectLocation: 'يرجى تحديد موقعك لعرض الخدمات المتاحة بالقرب منك',
        changeLocationLater: 'يمكنك تغيير موقعك لاحقاً في أي وقت',
        discoverServices: 'اكتشف الخدمات في',
        trustedPlatform: 'منصتك الموثوقة للعثور على أفضل مقدمي الخدمات والمنتجات في منطقتك',
        addServiceNow: 'أضف خدمتك الآن',
        startFree: 'ابدأ مجاناً',
        featuredIn: 'خدمات مميزة في',
        premiumOnly: 'مميز',
        browseCategories: 'تصفح الأقسام',
        viewAll: 'عرض الكل',
        joinNetwork: 'انضم إلى شبكتنا',
        joinSubtitle: 'سجل الآن وابدأ بعرض خدماتك لآلاف العملاء المحتملين',
        signUpFree: 'سجل مجاناً',
        learnMore: 'اعرف أكثر',
        beFirst: 'كن أول من ينشر في المجتمع',
        totalUsers: 'إجمالي المستخدمين',
        totalPosts: 'إجمالي المنشورات',
        totalServices: 'إجمالي الخدمات',
        totalReviews: 'إجمالي التقييمات',
        searchUsers: 'ابحث عن مستخدم بالاسم أو الإيميل...',
        noUsersFound: 'لا يوجد مستخدمون مطابقون',
        vipMembers: 'أعضاء VIP',
        adAccounts: 'حسابات إعلانية',
        regularUsers: 'مستخدمون عاديون',
        bannedUsers: 'مستخدمون محظورون',
        recentActivity: 'النشاط الأخير',
        platformStats: 'إحصائيات المنصة',
        joinedAt: 'انضم في',
        serviceNameLabel: 'اسم الخدمة/المنتج',
        serviceNamePlaceholder: 'مثال: دروس تقوية في الرياضيات',
        selectCategoryLabel: 'اختر القسم',
        selectCategoryPlaceholder: 'اختر القسم المناسب',
        selectAgeCategoryLabel: 'تحديد الفئة',
        selectAgeCategoryPlaceholder: 'اختر الفئة',
        ageAll: 'الكل (رجالي, نسائي, أطفال)',
        ageMen: 'رجالي',
        ageWomen: 'نسائي',
        ageChildren: 'أطفال',
        countryLabel: 'الدولة',
        selectCountryPlaceholder: 'اختر الدولة',
        cityLabel: 'المدينة',
        selectCityPlaceholder: 'اختر المدينة',
        serviceDescriptionLabel: 'وصف الخدمة',
        serviceDescriptionPlaceholder: 'اكتب وصفاً جذاباً يوضح تفاصيل خدمتك...',
        serviceImageLabel: 'صورة الخدمة',
        contactInfoTitle: 'معلومات التواصل',
        providerNameLabel: 'اسمك أو اسم شركتك',
        providerNamePlaceholder: 'مثال: شركة النجاح للخدمات',
        whatsappLabel: 'رقم واتساب',
        subscriptionComingTitle: 'نظام الاشتراكات قادم قريباً!',
        subscriptionComingDesc: 'حالياً، جميع الخدمات المضافة ستكون ضمن الخطة الأساسية مجاناً. سيتم تفعيل نظام الاشتراكات المدفوعة قريباً لمميزات إضافية مثل الظهور في القسم المميز.',
        addServiceTitle: 'أضف خدمتك أو منتجك',
        addServiceDesc: 'املأ النموذج التالي لعرض خدمتك في المنصة الرسمية لآلاف العملاء المحتملين في منطقتك.',
        sendingService: 'جاري الإرسال...',
        submitServiceBtn: 'إضافة الخدمة',
        registeredServicesLabel: 'الخدمات المسجلة',
        loginRequiredTitle: 'يجب تسجيل الدخول أولاً',
        loginRequiredDesc: 'سجل دخولك بحساب Google عشان تقدر تضيف خدمتك وتديرها بأمان',
        loginWithGoogleBtn: 'تسجيل الدخول بحساب Google',
        limitReachedTitle: 'وصلت للحد الأقصى',
        limitReachedSubtitle: 'لحماية المنصة من الإساءة',
        limitReachedNote: 'يمكن لكل حساب إضافة {max} خدمات كحد أقصى. لإضافة خدمة جديدة، يجب حذف إحدى خدماتك الحالية أولاً.',
        manageMyServicesBtn: 'إدارة خدماتي الحالية',
    },
    en: {
        home: 'Home',
        community: 'Community',
        addService: 'Add Service',
        search: 'Search',
        settings: 'Settings',
        back: 'Back',
        premium: 'Premium',
        by: 'By',
        views: 'views',
        contactMethods: 'Contact Methods',
        call: 'Call',
        whatsapp: 'WhatsApp',
        email: 'Email',
        noContact: 'No contact methods available',
        reviews: 'Reviews',
        addReview: 'Add your review',
        yourName: 'Your name',
        yourComment: 'Your comment',
        submitReview: 'Submit review',
        noReviews: 'No reviews yet',
        follow: 'Follow',
        unfollow: 'Unfollow',
        followers: 'Followers',
        following: 'Following',
        forYou: 'For You',
        followingFeed: 'Following',
        noPostsYet: 'No posts yet',
        like: 'Like',
        love: 'Love',
        comment: 'Comment',
        share: 'Share',
        reply: 'Reply',
        replies: 'Replies',
        likeComment: 'Like',
        writeComment: 'Write a comment...',
        writeReply: 'Write a reply...',
        whatsOnMind: "What's on your mind?",
        publish: 'Publish',
        addPhoto: 'Add photo',
        addMorePhotos: 'Add more photos',
        accountSettings: 'Account Settings',
        customizeAccount: 'Customize your personal account settings',
        savedSuccessfully: 'Saved successfully',
        personalInfo: 'Personal Information',
        fullNameLabel: 'Full Name',
        enterFullName: 'Enter your full name',
        phoneNumber: 'Phone Number',
        phonePlaceholder: '05xxxxxxxx',
        emailAddress: 'Email Address',
        emailCannotChange: 'Email cannot be changed',
        bio: 'Bio',
        bioPlaceholder: 'Write a short bio about yourself...',
        notificationSettings: 'Notification Settings',
        generalNotifications: 'General Notifications',
        generalNotificationsDesc: 'Receive general in-app notifications',
        emailNotifications: 'Email Notifications',
        emailNotificationsDesc: 'Receive notifications via email',
        marketingEmails: 'Marketing Emails',
        marketingEmailsDesc: 'Receive offers and platform updates',
        securityPrivacy: 'Security & Privacy',
        accountProtection: 'Account Protection',
        protectedByGoogle: 'Your account is protected via secure sign-in',
        googleAuthProtected: 'Account protected',
        saving: 'Saving...',
        saveSettings: 'Save Settings',
        welcome: 'Welcome',
        selectLocation: 'Please select your location to see services available near you',
        changeLocationLater: 'You can change your location anytime later',
        discoverServices: 'Discover services in',
        trustedPlatform: 'Your trusted platform to find the best service and product providers in your area',
        addServiceNow: 'Add Your Service Now',
        startFree: 'Start Free',
        featuredIn: 'Featured services in',
        premiumOnly: 'Premium',
        browseCategories: 'Browse Categories',
        viewAll: 'View all',
        joinNetwork: 'Join our network',
        joinSubtitle: 'Sign up now and start showcasing your services to thousands of potential clients',
        signUpFree: 'Sign up free',
        learnMore: 'Learn more',
        beFirst: 'Be the first to post in the community',
        totalUsers: 'Total Users',
        totalPosts: 'Total Posts',
        totalServices: 'Total Services',
        totalReviews: 'Total Reviews',
        searchUsers: 'Search by name or email...',
        noUsersFound: 'No matching users found',
        vipMembers: 'VIP Members',
        adAccounts: 'Ad Accounts',
        regularUsers: 'Regular Users',
        bannedUsers: 'Banned Users',
        recentActivity: 'Recent Activity',
        platformStats: 'Platform Statistics',
        joinedAt: 'Joined',
        serviceNameLabel: 'Service/Product Name',
        serviceNamePlaceholder: 'e.g., Math Tutoring',
        selectCategoryLabel: 'Select Category',
        selectCategoryPlaceholder: 'Choose the right category',
        selectAgeCategoryLabel: 'Select Type',
        selectAgeCategoryPlaceholder: 'Choose a type',
        ageAll: 'All (Men, Women, Kids)',
        ageMen: 'Men',
        ageWomen: 'Women',
        ageChildren: 'Kids',
        countryLabel: 'Country',
        selectCountryPlaceholder: 'Select country',
        cityLabel: 'City',
        selectCityPlaceholder: 'Select city',
        serviceDescriptionLabel: 'Service Description',
        serviceDescriptionPlaceholder: 'Write an attractive description explaining your service details...',
        serviceImageLabel: 'Service Image',
        contactInfoTitle: 'Contact Information',
        providerNameLabel: 'Your Name / Company Name',
        providerNamePlaceholder: 'e.g., Success Co.',
        whatsappLabel: 'WhatsApp Number',
        subscriptionComingTitle: 'Subscription System Coming Soon!',
        subscriptionComingDesc: 'Currently, all added services are 100% free under the basic plan. A paid subscription system will be available soon for extra features like featured placement.',
        addServiceTitle: 'Add Your Service or Product',
        addServiceDesc: 'Fill out the form below to display your service to thousands of potential clients in your area.',
        sendingService: 'Sending...',
        submitServiceBtn: 'Add Service',
        registeredServicesLabel: 'Registered Services',
        loginRequiredTitle: 'You need to sign in first',
        loginRequiredDesc: 'Sign in with Google so you can add and manage your service securely',
        loginWithGoogleBtn: 'Sign in with Google',
        limitReachedTitle: "You've reached the limit",
        limitReachedSubtitle: 'To protect the platform from abuse',
        limitReachedNote: 'Each account can add up to {max} services. To add a new one, delete an existing service first.',
        manageMyServicesBtn: 'Manage My Services',
    },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [language, setLanguageState] = useState(() => localStorage.getItem('appLanguage') || 'ar');

    const dir = language === 'ar' ? 'rtl' : 'ltr';

    useEffect(() => {
        document.documentElement.dir = dir;
        document.documentElement.lang = language;
    }, [dir, language]);

    const setLanguage = (lang) => {
        setLanguageState(lang);
        localStorage.setItem('appLanguage', lang);
    };

    const t = (key) => translations[language]?.[key] ?? translations.ar[key] ?? key;

    return (
        <LanguageContext.Provider value={{ language, dir, t, setLanguage, changeLanguage: setLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) {
        return { language: 'ar', dir: 'rtl', t: (k) => k, setLanguage: () => {}, changeLanguage: () => {} };
    }
    return ctx;
}
